### ISSUE TITLE
スロット制限を実装

### ISSUE THREAD

**Issue by Harineko0** [MincraServer/MincraMagics#4]
# TODO
- [ ] MagicStuffNBTに追加
- [ ] MaterialEditorで制限とテクスチャを追加

# 仕様
- 各スロットの有効・無効、パッシブスロット数を設定する
- OraxenのConfigは以下のような感じ。明示していない場合、アクティブスロットはenabled・パッシブスロットは0となる
```YAML
      slot:
        right: enabled
        left: disabled
        passive: 2
```
